default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  #host: <%= ENV['POSTGRES_HOST'] %>
  host: localhost

development:
  <<: *default
  database: capstone-demoapp_development

test:
  <<: *default
  database: capstone-demoapp_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
